azinchen/nordvpn

root/app/createvpnconfig.sh
root/etc/cont-init.d/10-firewall

During the creation of the vpn config file a iptable rule will be added, which allows the communication to selected vpn server also the previous server rule will be deleted.
Therefore we don't need it anymore to open the udp/tcp port 1194 for all ip addresses.
Also fixes the tcp bug, which requires a connect on port 443. Until now only port 1194 was open.

Iptables: allow only currently connected vpn server

---

Dockerfile

Fix Snyk report warnings
* CVE-2021-22945, curl to version 7.79.0-r0 or higher
* CVE-2021-22946, curl to version 7.79.0-r0 or higher
* CVE-2021-22947, curl to version 7.79.0-r0 or higher

Fix Snyk report warnings

---

Dockerfile

Fix Snyk alerts
* CVE-2021-42374: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42375: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42378: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42379: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42380: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42381: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42382: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42383: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42384: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42385: Upgrade busybox to version 1.33.1-r4 or higher
* CVE-2021-42386: Upgrade busybox to version 1.33.1-r4 or higher

Snyk alerts 11/20/21

---

.gitignore
Dockerfile
root/usr/bin/createvpnconfig.sh

Changes in this PR:
- Allow selecting a specific server instead of getting a random server. ( fixes #139 ) [Added `bind-tools` package so I could use `host`. I tried via `ping`, but I always got errors with that.]
- Security upgrade of alpine (I saw other PRs open to do just that same thing)
- Upgrade of curl to `r1`. `r0` would break the build
- Cleaned up the main script to:
* removal of double quoting (for example "some ""$var"" defined" can be written as "some $var defined".
* adding of quoting to ensure correctness [for example `$(getgrouptitle $value)` --> `$(getgrouptitle "$value")`
* `! -z` --> `-n`
The main change is the first bit.
So now I could call the container with `--env "COUNTRY=DE205"` and I'll always be getting that exact server (faked the load to be 0 so it's on top of …

Changes to allow selecting a specific server

---

.github/workflows/update_readme.yml

Potential fix for [https://github.com/azinchen/nordvpn/security/code-scanning/693](https://github.com/azinchen/nordvpn/security/code-scanning/693)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the minimal permissions required for the workflow to function correctly. Since the workflow involves creating pull requests and updating files, the permissions should include `contents: write` and `pull-requests: write`. Adding the `permissions` block at the root level of the workflow ensures that all jobs inherit these permissions unless explicitly overridden.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 693: Workflow does not contain permissions

---

.github/workflows/update_configs.yml

Potential fix for [https://github.com/azinchen/nordvpn/security/code-scanning/690](https://github.com/azinchen/nordvpn/security/code-scanning/690)
To fix the issue, we will add a `permissions` block to the root of the workflow file. This block will define the minimal permissions required for the workflow to function correctly. Specifically:
- The `contents: read` permission is needed to allow the workflow to read repository contents.
- The `pull-requests: write` permission is required for the `peter-evans/create-pull-request` action to create and manage pull requests.
The `permissions` block will be added at the root level of the workflow file to apply to all jobs within the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 690: Workflow does not contain permissions

---

.github/workflows/deploy.yml

Potential fix for [https://github.com/azinchen/nordvpn/security/code-scanning/687](https://github.com/azinchen/nordvpn/security/code-scanning/687)
To fix the issue, we need to explicitly define the permissions for the workflow. The `permissions` key should be added at the root level of the workflow to apply to all jobs, or it can be added to individual jobs to tailor permissions for specific tasks. In this case, the minimal permissions required for the workflow are:
- `contents: read` for accessing repository contents.
- `packages: write` for pushing Docker images to GitHub Container Registry.
- `actions: read` for using actions.
The `permissions` block will be added at the root level of the workflow to ensure all jobs inherit the least privilege permissions.
---
_Suggested fixes powered …

Potential fix for code scanning alert no. 687: Workflow does not contain permissions

---

.github/workflows/update-apk-versions.yml

Potential fix for [https://github.com/azinchen/nordvpn/security/code-scanning/685](https://github.com/azinchen/nordvpn/security/code-scanning/685)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the minimal permissions required for the workflow to function correctly. Based on the tasks performed in the workflow:
- `contents: write` is needed for the `actions/checkout` step and to commit changes.
- `pull-requests: write` is required for the `peter-evans/create-pull-request` action to create and manage pull requests.
The `permissions` block will be added after the `name` field at the top of the workflow file.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 685: Workflow does not contain permissions

---

.github/workflows/docker-image-security.yml

Potential fix for [https://github.com/azinchen/nordvpn/security/code-scanning/684](https://github.com/azinchen/nordvpn/security/code-scanning/684)
To address the issue, we will add a `permissions` block at the root level of the workflow file. This block will explicitly define the permissions required for the workflow, limiting the `GITHUB_TOKEN` to read-only access to repository contents. Since the workflow uploads SARIF files to the GitHub Security tab, no additional write permissions are necessary.
The `permissions` block will be added immediately after the `name` field at the top of the file. This ensures that the permissions apply to all jobs in the workflow unless overridden by a job-specific `permissions` block.
---
_Suggested fixes powered by Copilot Autofix. Review carefully …

Potential fix for code scanning alert no. 684: Workflow does not contain permissions

---

.github/workflows/update_configs.yml

The `update_configs.yml` GitHub Actions workflow has been consistently failing for the past 6 days with permission errors:
```
remote: Permission to azinchen/nordvpn.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/azinchen/nordvpn/': The requested URL returned error: 403
```
The workflow was configured with `contents: read` permission, but the `peter-evans/create-pull-request` action requires `contents: write` permission to:
- Create new branches
- Push commits to those branches  
- Create pull requests from those branches
- Changed permissions in `.github/workflows/update_configs.yml` from `contents: read` to `contents: write`
After this change, the workflow will be able to:
- Successfully create branches for config updates
- Push commits to those branches …

Fix GitHub Actions workflow permissions causing update_configs.yml failures

---

.github/workflows/cleanup-registries.yml

This PR implements automated cleanup of old container images from both Docker Hub and GitHub Container Registry to manage storage costs and keep registries organized.
- ✅ **New workflow**: `.github/workflows/cleanup-registries.yml`
- 🗓️ **Daily schedule**: Runs automatically at 2:00 AM UTC
- 🎯 **Dual registry support**: Docker Hub (`azinchen/nordvpn`) and GHCR (`ghcr.io/azinchen/nordvpn`)
- 🛡️ **Smart protection**: Preserves `latest` tag and highest patch versions
- ⚙️ **Configurable retention**: 365 days for releases, 90 days for dev tags
- 🧪 **Manual execution**: Support for dry-run testing and custom parameters
- **Conservative defaults**: Long retention periods to ensure important images are kept
- **Version-aware protection**: Uses `--protect-latest-per patch` to keep latest patch …

feat: add automated container registry cleanup workflow

---

.github/workflows/maintenance-updates.yml

The automated maintenance workflow was failing to generate proper README files due to incorrect jq filter escaping. The jq string interpolation syntax was double-escaped (`\\(...)` instead of `\(...)`), causing jq command failures.
In GitHub Actions YAML, the jq filters were using double backslashes:
- ❌ `"\\(.[0]) | \\(.[1]) | \\(.[2])"`
- ✅ `"\(.[0]) | \(.[1]) | \(.[2])"`
- Fixed jq string interpolation escaping in all matrix file definitions:
- **CITIES**: `[.name, .code, .id, .name, .id]`
- **COUNTRIES**: `[.name, .code, .id]`
- **TECHNOLOGIES**: `[.name, .identifier, .id]`
- **GROUPS**: `[.title, .identifier, .id]`
- ✅ Fixes README generation failures
- ✅ Ensures proper markdown table formatting
- ✅ Resolves issues from PRs #696, #697, #698, #699
- ✅ Maintains separate PR creation …

🔧 Fix jq filter escaping in maintenance workflow

---

.github/workflows/ci-build-deploy.yml

This PR implements the deployment strategy changes proposed in issue #709 to improve release management and follow industry best practices.
- **Before**: Both master branch and tags triggered production deployments
- **After**: Only git tags trigger production deployments to DockerHub
- **Tags**: Deploy to both DockerHub and GHCR with versioned tag + `latest`
- **Master**: Deploy only to GHCR with `dev` tag (was `master`)
- **Branches**: Deploy only to GHCR with sanitized branch name
- Consolidated build steps (removed separate `latest` tag step)
- Simplified secret validation (only check DockerHub creds for tags)
- Updated metadata reporting to work for all builds
- Improved comments and documentation
✅ **Better Release Management**: Clear separation between dev and prod  
✅ **Risk …

refactor: change production deployment strategy to tags-only

---

.github/workflows/ci-build-deploy.yml

This PR fixes the Docker tag naming inconsistency by removing the 'v' prefix from container image tags for production releases.
Currently, when Git tags are created with a 'v' prefix (e.g., ), the Docker container images are also tagged with the 'v' prefix, which is inconsistent with Docker tagging best practices.
Modified the CI/CD workflow in  to strip the 'v' prefix from tag names when creating Docker image tags for production releases using bash parameter expansion `${GITHUB_REF_NAME#v}`.
- **Before**: `IMAGE_TAG=${GITHUB_REF_NAME}` (uses tag name as-is)
- **After**: `IMAGE_TAG=${GITHUB_REF_NAME#v}` (removes 'v' prefix if present)
- Git tag: `v1.0.0` → Docker tag: `1.0.0`
- Git tag: `1.0.0` → Docker tag: `1.0.0`
- ✅ Ensures consistent Docker tag naming regardless of Git tag format
- ✅ …

Fix: Remove 'v' prefix from Docker tag names for production releases

---

root/etc/s6-overlay/s6-rc.d/init-createauth/dependencies

Fixes #743
This PR adds the missing dependencies file for the init-createauth service in the s6-overlay configuration.
- Added `root/etc/s6-overlay/s6-rc.d/init-createauth/dependencies` file
- Specifies `init-adduser` as a prerequisite service
The init-createauth service was missing its dependencies file, which could lead to improper service initialization order. Without this file, the service might start before its prerequisite services, potentially causing initialization failures.

Add dependencies file for init-createauth service

---

.github/workflows/maintenance-updates.yml

Fixes #745
This PR enhances the maintenance workflow to include server count information in the generated markdown files, providing users with valuable server availability data.
- **COUNTRIES.md**: Added 'Servers' column showing total servers per country
- **CITIES.md**: Added 'Servers' columns for both country totals and city-specific counts
- **countries.json**: Preserved server count data (only removed hub_score field)
- Updated jq filters to extract `serverCount` from NordVPN API responses
- COUNTRIES.md: `Country | Code | ID`
- CITIES.md: `Country | Code | ID | City | ID`
- COUNTRIES.md: `Country | Code | ID | Servers`
- CITIES.md: `Country | Code | ID | Servers | City | ID | Servers`
- Users can see current server availability for informed decision-making
- More complete data …

feat: add server count information to markdown files

---

.github/workflows/maintenance-updates.yml

This PR modifies the maintenance workflow to sort the IP addresses retrieved from `api.nordvpn.com` before setting them in the `NORDVPNAPI_IP` environment variable in the Dockerfile.
Changes:
- Added `sort -V` to the command pipeline in `maintenance-updates.yml` to ensure IP addresses are sorted in version order.
Reason: Sorting the IPs provides consistent ordering, preventing unnecessary diffs in the Dockerfile due to random IP sequence variations from the DNS lookup. This improves reproducibility and reduces noise in automated updates.

Sort NordVPN API IPs in maintenance workflow

---

root/usr/local/bin/network-diagnostic

This PR fixes the network-diagnostic script that was showing '?' placeholders instead of actual VPN connection information.
- **POSIX sh compatibility**: Replaced bash-specific syntax with POSIX-compatible commands
- **Robust data extraction**: Implemented proper parsing from OpenVPN management interface
- **Fallback mechanisms**: Added config file parsing for Common Name and Trusted Peer when management interface is unavailable
- **Variable initialization**: Fixed undefined variable issues that caused '?' placeholders
- **Complete diagnostics**: Ensured all VPN connection parameters are properly displayed
The script now correctly displays:
- Server hostname (e.g., es239.nordvpn.com)
- Trusted peer IP/port (e.g., 185.214.97.138:1194)
- Interface configuration (local/remote IPs)
- Protocol …

Fix network-diagnostic script to properly extract VPN connection details

---

root/etc/s6-overlay/s6-rc.d/init-firewall/run
root/usr/local/bin/network-diagnostic

This PR fixes the script name references in network-diagnostic and updates firewall rules for more specific interface matching.
Changes:
- Update network-diagnostic script comments and usage to use correct script name
- Change firewall rules from tun+ to tun0 for more specific interface matching

Fix script name in network-diagnostic and update firewall rules

---

.github/workflows/maintenance-updates.yml

Remove the 'if' condition that prevented creating PR for APK updates when no updates were found. Now PR will be created regardless.
This ensures that the APK update job always attempts to create a PR, even if no packages were updated, which can be useful for tracking the workflow runs.

fix: remove condition for APK PR creation

---

scripts/update-apk-versions.sh

Fix the APK package update script to properly count total packages checked and packages updated.
**Issue:** The script was using a piped while loop which runs in a subshell, preventing TOTAL_PACKAGES and UPDATED_COUNT variables from being updated in the main shell. This caused the summary to always show 0 packages checked and 0 updated, even when packages were actually processed.
**Fix:** Changed the loop from:
To:
This ensures the variables are updated in the main shell scope.
**Result:** The script now correctly reports the number of packages checked and updated in the summary output.

fix: correct package counting in APK update script

---

.github/workflows/maintenance-updates.yml

Fix the APK package update workflow to properly parse the script output and create PRs with correct information.
**Changes:**
- Capture the output of the update-apk-versions.sh script
- Parse the summary section to extract total packages checked, updated count, and list of updated packages
- Set proper GITHUB_OUTPUT variables for use in PR creation
- Restore the condition to only create PR when packages are actually updated
- Ensure PR body includes detailed list of updated packages with version changes
This resolves the issue where PRs were created with '0 of 0 checked' and missing package update details.

fix: parse APK update script output for proper PR creation
